### ISSUE TITLE
JavaScript structure issues causing Dev Console error messages

### ISSUE THREAD

**Issue by d2s** [dhoman/homan-io#1]
Noticed various Developer Console error messages on the [About](https://www.homan.io/about/) page. Same problem is visible on all of the other pages on your site. Not exactly sure how it affects the functionality of the site, but at least the error is visible if people look at the Console.

```txt
Uncaught TypeError: Cannot read property 'imageData' of null at onmessage
```

<img width="720" alt="2019-02-22-website-homan-io-dev-console-errors" src="https://user-images.githubusercontent.com/135053/53255354-2006f300-36ce-11e9-8a33-29361ea59cf9.PNG">

**Comment by dhoman** [comment]
This issue seems to no longer be occurring
